name: "workflow for self-hosted testing"
on:
  push:
    branches:["main]
  pull:
    braches:["main"]
  workflow_dispatch:
jobs:
   build1:
       name: testing
       runs-on: self-hosted
       steps:
           - uses: actions/checkout@v3
             with:
               fetch-depth: 0
