name: test workflow to print echo
on:
  push:
    branches:
       - main
  pull_request:
    branches:
       - main
  workflow_dispatch:
jobs:
  buildjobs:
        name: build jobs to print single & multiple lines
        runs-on: self-hosted
        steps:
              - name: checkout repository
                uses: actions/checkout@v3
                
              - name: list of files
                run: |
                    pwd
                    ls -lah
              - name: print multipe lines
                run: | 
                     echo " first line"
                     echo " second line"
                
              - name: installing python
                uses: actions/setup-python@v4
                with:
                   python-version: '3.10'
              - name: Running Python Script  
                run: python -c "print('First Python Print Program')"
                     
           
  
